spring:
  application:
    name: integrator-service
    profiles: dev
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: 27017
      database: mydatabase
      username: root
      password: secret
      authentication-database: admin
  redis:
    host: ${REDIS_HOST:localhost}
    port: 6379
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:broker:29092}
    producer:
      group-id: api-gateways
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      properties:
        spring:
          json:
            trusted:
              packages: '*'
            value:
              type: com.fachri.bproject.model.FlightSearchRequest
      group-id: api-gateways
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

server:
  port: 8081

integration:
  abacus-ndc:
    baseUrl: ${ABACUS_NDC_BASE_URL:http://localhost:9090}
  pkfare:
    baseUrl: ${PKFARE_BASE_URL:http://localhost:9090}