spring:
  application:
    name: aggregator-service
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: mydatabase
      username: root
      password: secret
  redis:
    host: ${REDIS_HOST:localhost}
    port: 6379
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:9092
    consumer:
      group-id: api-gateways
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer